version: "3"

services:
  api:
    build: ./docker/api
    image: skyeanka/keiba-ataru-backend
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11