# Generated by Django 2.2 on 2019-10-26 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raceset_name', models.CharField(max_length=100, verbose_name='競走名')),
                ('date', models.DateField(verbose_name='実施日')),
                ('racecourse', models.CharField(max_length=100, verbose_name='競馬場')),
            ],
            options={
                'db_table': 'raceset',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('race_name', models.CharField(max_length=100, verbose_name='レース名')),
                ('race_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='レースナンバー')),
                ('starttime', models.TimeField(verbose_name='レース開始時間')),
                ('raceset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='apiv1.RaceSet', verbose_name='競走名ID')),
            ],
            options={
                'db_table': 'race',
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horse_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='馬順')),
                ('horse_name', models.CharField(max_length=100, verbose_name='馬名')),
                ('trio_pred', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='三連複予想')),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='apiv1.Race', verbose_name='レースID')),
            ],
            options={
                'db_table': 'horse',
                'unique_together': {('race_id', 'horse_number')},
            },
        ),
    ]
